version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nba-postgres
    environment:
      POSTGRES_DB: nba_stats
      POSTGRES_USER: nba_user
      POSTGRES_PASSWORD: nba_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nba-network

  webapp:
    build: .
    container_name: nba-webapp
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - DATABASE_URL=postgresql://nba_user:nba_password@postgres:5432/nba_stats
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - nba-network
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        echo 'Setting up database schema...' &&
        npx prisma db push &&
        echo 'Seeding database...' &&
        npx prisma db seed &&
        echo 'Starting development server...' &&
        npm run dev
      "

volumes:
  postgres_data:

networks:
  nba-network:
    driver: bridge